# Generated by Django 4.0.5 on 2022-06-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150, verbose_name='Código')),
                ('stock', models.CharField(max_length=255, verbose_name='Ação')),
                ('tipo', models.CharField(max_length=150, verbose_name='Tipo')),
                ('qtd_Teorica', models.IntegerField(verbose_name='Qtde. Teorica')),
                ('part', models.FloatField(verbose_name='Part.(%)')),
            ],
        ),
    ]
