# Generated by Django 4.0.5 on 2022-06-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='part',
            field=models.CharField(max_length=150, verbose_name='Part.(%)'),
        ),
    ]
