# Generated by Django 4.0.5 on 2022-06-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_alter_price_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='qtd_Teorica',
            field=models.CharField(max_length=255, verbose_name='Qtde. Teorica'),
        ),
    ]
